services:
  api-1:
    build: .
    image: ${IMAGE_NAME}
    environment:
      INSTANCE_ID: api-1
    ports:
      - "${HOST_PORT_1}:3000"

  api-2:
    build: .
    image: ${IMAGE_NAME}
    environment:
      INSTANCE_ID: api-2
    ports:
      - "${HOST_PORT_2}:3000"

  api-3:
    build: .
    image: ${IMAGE_NAME}
    environment:
      INSTANCE_ID: api-3
    ports:
      - "${HOST_PORT_3}:3000"