events {}

http {
    upstream backend {
        server api-1:3000;
        server api-2:3000;
        server api-3:3000;
    }

    log_format upstream_log '$remote_addr - [$upstream_addr] $request $status';

    server {
        listen 80;

        access_log /var/log/nginx/access.log upstream_log;

        location / {
            proxy_pass http://backend;
        }
    }
}